### PR TITLE
TRITON-2412 sdc-headnode uses improper curl flag --progress

### PR DESCRIPTION
**Pull request by danmcd**

### CODE REVIEW

**Review by teutat3s — APPROVED** [review]
I had a quick look into `man curl' and this looks good 👍 Good catch.

Only question that comes to my mind: will this work with any version of curl or is a coordinated update needed?

**Review by travispaul — APPROVED** [review]

**Comment by danmcd** [comment]
> Only question that comes to my mind: will this work with any version of curl or is a coordinated update needed?

No coordination is needed save this MUST be in place (or patched by hand) prior to OS-8491 getting deployed.  `--progress-bar` should've been there from the start.  E.g. piadm(8) uses that if you invoke with the -v option.

**Review by bahamat — CHANGES_REQUESTED** [review]
This must be tested with older platforms before being merged

**Review by bahamat — APPROVED** [review]
OK, this is approved.

My concern was whether or not the previous version of curl (7.51.0) supports `--progress-bar` or only `--progress`. I've always used it as `--progress`, but I guess that was a shorthand compat in older versions of curl that was eliminated in 8.x. The canonical long flag seems to have always been `--progress-bar` (or at least for as long as it matters for our platform images).

**Pull request merged**
